version: '3.8'

services:
  edital:
    build: ./edital-service/
    container_name: edital_service
    ports:
      - "8080:8080"
    depends_on:
      - edital_db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_EDITAL_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_EDITAL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_EDITAL_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - gradle_cache_edital:/root/.gradle

  pesq_empre:
    build: ./pesquisador-empreendedor/
    container_name: pesq_empr_service
    ports:
      - "8081:8080"
    depends_on:
      - pesquisador_empreendedor_db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_PESQUISADOR_EMPREENDEDOR_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_PESQUISADOR_EMPREENDEDOR_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PESQUISADOR_EMPREENDEDOR_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - gradle_cache_pesq:/root/.gradle
  
  edital_db:
    image: postgres:13
    container_name: edital_db
    environment:
      POSTGRES_USER: ${POSTGRES_EDITAL_USER}
      POSTGRES_PASSWORD: ${POSTGRES_EDITAL_PASSWORD}
      POSTGRES_DB: ${POSTGRES_EDITAL_DB}
    volumes:
      - postgres_data_edital:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pesquisador_empreendedor_db:
    image: postgres:13
    container_name: pesquisador_empreendedor_db
    environment:
      POSTGRES_USER: ${POSTGRES_PESQUISADOR_EMPREENDEDOR_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PESQUISADOR_EMPREENDEDOR_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PESQUISADOR_EMPREENDEDOR_DB}
    volumes:
      - postgres_data_pesq:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data_edital:
  postgres_data_pesq:
  gradle_cache_edital:
  gradle_cache_pesq: