services:
  editaldb:
    image: postgres:13
    container_name: editaldb
    environment:
      POSTGRES_USER: ${POSTGRES_EDITAL_USER}
      POSTGRES_PASSWORD: ${POSTGRES_EDITAL_PASSWORD}
      POSTGRES_DB: ${POSTGRES_EDITAL_DB}
    volumes:
      - postgres_data_edital:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  pesquisadorempreendedordb:
    image: postgres:13
    container_name: pesquisadorempreendedordb
    environment:
      POSTGRES_USER: ${POSTGRES_PESQUISADOR_EMPREENDEDOR_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PESQUISADOR_EMPREENDEDOR_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PESQUISADOR_EMPREENDEDOR_DB}
    volumes:
      - postgres_data_pesq:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  gateway: 
    build: ./gateway/
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka:
        condition: service_healthy
  eureka: 
    build: ./eureka-sd/
    container_name: eureka
    ports:
      - "8761:8761"
    volumes:
      - gradle_cache_eureka:/root/.gradle
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
  llmcommunication:
    build: ./llmcommunication/
    container_name: llmcommunication
    depends_on:
      eureka:
        condition: service_healthy
    environment:
      - CHAVE_API_GEMINI=${CHAVE_API_GEMINI}
    volumes:
      - gradle_cache_llm:/root/.gradle
  edital:
    build: ./edital-service/
    container_name: edital_service
    depends_on:
      eureka:
        condition: service_healthy
      editaldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_EDITAL_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_EDITAL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_EDITAL_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_EDITAL=${EUREKA_CLIENT_EDITAL}
      - EUREKA_ADDRESS_HOST=${EUREKA_ADDRESS_HOST}
      - PATH_TO_FILES=${PATH_TO_FILES}
    volumes:
      - eureka-sd:/eureka-sd
      - gradle_cache_edital:/root/.gradle
  pesq_empre:
    build: ./pesquisador-empreendedor/
    container_name: pesq_empr_service
    depends_on:
      eureka:
        condition: service_healthy
      pesquisadorempreendedordb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_PESQUISADOR_EMPREENDEDOR_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_PESQUISADOR_EMPREENDEDOR_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PESQUISADOR_EMPREENDEDOR_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - gradle_cache_pesq:/root/.gradle
  


volumes:
  postgres_data_edital:
  postgres_data_pesq:
  gradle_cache_edital:
  gradle_cache_pesq:
  gradle_cache_eureka:
  gradle_cache_llm:
  eureka-sd: